Add platform macros
godotengine/godot-cpp pull request #1188
Opened 2023-07-22 12:48 UTC by adamscott

Add platform macros, like `LINUX_ENABLED` and `UNIX_ENABLED` on Linux, `MACOS_ENABLED`, `UNIX_ENABLED`, `COREAUDIO_ENABLED`, `COREMIDI_ENABLED` on macos, and `WINDOWS_ENABLED`, `WASAPI_ENABLED`, `WINMIDI_ENABLED` on Windows.

2023-07-22 12:49 UTC, adamscott commented on SConstruct
> +    env.Append(CPPDEFINES=["LINUX_ENABLED", "UNIX_ENABLED"])
Is there a reason that GDExtension doesn't build the "linuxbsd" platform instead of just "linux"?

2023-07-22 12:55 UTC, dsnopek commented
Thanks! I haven't had a chance to do a proper review yet, but I think this is a great idea

2023-07-23 16:48 UTC, Faless requested changes
Please move the flags to the dedicated platform tools in `tools`, inside the `generate` function.
These are the "equivalent" of upstream Godot `configure` functions inside `platform/name/detect.py`:
- `tools/windows.py`
- `tools/linux.py`
- `tools/macos.py`
- `tools/ios.py`
- etc.

This will also simplify the code as you can just add the flags there without having to check for the `env["platform"]` variables (the `generate` function is called only when the given platform is selected).

2023-07-23 17:30 UTC, adamscott commented
> Please move the flags to the dedicated platform tools in `tools`, inside the `generate` function.

Yes, I saw this yesterday, but didn't have time to change it. Thanks, will do.

2023-07-23 18:58 UTC, Faless requested changes
See my 2 comments, I will open a separate PR to merge the `osxcross` tools and reduce confusion.

2023-07-23 18:58 UTC, Faless commented on tools/ios_osxcross.py
> +    env.Append(CPPDEFINES=["IOS_ENABLED", "UNIX_ENABLED", "COREAUDIO_ENABLED"])
This is not needed, as this tool is included by `ios.py` (I think we should actually move the code in this tool to be the same `ios.py` file).
```suggestion
```

2023-07-23 18:58 UTC, Faless commented on tools/macos_osxcross.py
> +    env.Append(CPPDEFINES=["MACOS_ENABLED", "UNIX_ENABLED", "COREAUDIO_ENABLED", "COREMIDI_ENABLED"])
Like `ios_oscross.py`, this is also included by `macos.py`,

```suggestion
```

2023-07-23 20:51 UTC, Faless approved these changes
This looks good now :+1: .
The only thing I'm not sure about is having `COREAUDIO_ENABLED`, `COREMIDI_ENABLED` on ios/macos, and `WASAPI_ENABLED`, `WINMIDI_ENABLED` on windows.

Why are they useful? I think those are there to control godot driver internals, and if they can't be disabled on those platforms, then extensions could just check for `WINDOWS_ENABLED`/`MACOS_ENABLED`.

2023-07-23 23:24 UTC, adamscott commented
@Faless I just removed the non-platform related macros!

2023-07-25 22:43 UTC, dsnopek approved these changes
Thanks!

This looks great to me. I did a quick test, and I can see the Linux defines showing up as expected.

2023-07-31 20:38 UTC, merged