Added newer Variant types to `typed_array.hpp`
godotengine/godot-cpp pull request #1384
Opened 2024-02-06 15:23 UTC by allenwp

This is a companion commit to the godot PR https://github.com/godotengine/godot/pull/87992 which fixes https://github.com/godotengine/godot/issues/87991

Currently in draft as I look into why IPAddress struct isn't included in godot-cpp...

2024-02-06 17:37 UTC, AThousandShips approved these changes
LGTM

2024-02-06 17:37 UTC, AThousandShips commented on include/godot_cpp/variant/typed_array.hpp
> +// MAKE_TYPED_ARRAY(IPAddress, Variant::STRING)
```suggestion
//MAKE_TYPED_ARRAY(IPAddress, Variant::STRING)
```
No space before code

2024-02-06 17:59 UTC, allenwp commented on include/godot_cpp/variant/typed_array.hpp
> +// MAKE_TYPED_ARRAY(IPAddress, Variant::STRING)
Good catch, thanks!

2024-02-06 18:15 UTC, AThousandShips requested changes

2024-02-06 18:15 UTC, AThousandShips commented on include/godot_cpp/core/type_info.hpp
Should probably be added here for completeness as they're added in the engine

2024-02-06 18:45 UTC, allenwp commented on include/godot_cpp/core/type_info.hpp
Good catch! I thought I had already checked for this, but I accidentally misread `MAKE_TYPE_INFO` in this file (which already has `Vector4`, etc.) as `MAKE_TYPED_ARRAY_INFO` (which you identified as not having `Vector4`). Thanks!

2024-02-06 18:55 UTC, AThousandShips approved these changes

2024-02-06 18:55 UTC, allenwp reviewed
Added MAKE_TYPED_ARRAY_INFO for new types.

2024-02-08 14:53 UTC, IvanInventor commented
That's still not all of the possible TypedArray types supported, see this
```
run/media/vano/hdd/Godot4/godot-cppscript-template/external/godot-cpp/include/godot_cpp/core/type_info.hpp:323:114: error: ‘get_class_static’ is not a member of ‘godot::PackedByteArray’
  323 |                 return make_property_info(Variant::Type::ARRAY, "", PROPERTY_HINT_ARRAY_TYPE, T::get_class_static());
      |                                                                                               ~~~~~~~~~~~~~~~~~~~^~
 ```
 or [this](https://discord.com/channels/212250894228652034/342047011778068481/1205065009579819028)
 
Basically, whole https://github.com/allenwp/godot-cpp/blob/349b5a3146404ce32c3b6ef8f7427af99fd9dcee/include/godot_cpp/core/type_info.hpp#L354-L388 list should be a copy-paste of whole https://github.com/allenwp/godot-cpp/blob/349b5a3146404ce32c3b6ef8f7427af99fd9dcee/include/godot_cpp/variant/typed_array.hpp#L80C1-L123 list with `_INFO` suffix, which is a working fix.
I suppose, same thing should be added to engine itself.

2024-02-12 14:14 UTC, allenwp commented
> That's still not all of the possible TypedArray types supported

This PR is just for syncing up godot-cpp with the main godot repo, specifically adding the new types like `Vector4`, `Vector4i`, and `Projection`.

All of the other missing types were likely intentionally excluded from godot-cpp because they do exist in the file, but are commented out, as AThousandShips mentioned.

It’s probably best to make a separate issue (and PR) in this repo regarding those missing `TypedArray` types.

2024-02-12 15:35 UTC, AThousandShips commented
Indeed, let's keep these separate, the other cases are an old issue and unsure why they are commented out, should be investigated and worked on separately

2024-02-12 16:07 UTC, dsnopek approved these changes
Looks good to me! Thanks :-)

2024-02-12 16:07 UTC, merged

2024-08-21 16:57 UTC, Innokentiy-Alaytsev commented
> Also undefined typed array templates after use to match Godot's typed_array.h.

So how can I declare custom typed arrays now?