Add Array:make macro
godotengine/godot-cpp pull request #646
Opened 2021-11-01 09:09 UTC by BastiaanOlij

Added support for our `Array::make` macro.

2021-11-01 12:11 UTC, Calinou requested changes

2021-11-01 12:11 UTC, Calinou commented on include/godot_cpp/variant/array_helpers.hpp
> +} // namespace godot
Add a newline at end of file:

```suggestion
} // namespace godot

```

2021-11-04 14:38 UTC, akien-mga commented on include/godot_cpp/variant/array_helpers.hpp
> +} // namespace godot
Still seems missing.

2021-11-10 00:34 UTC, BastiaanOlij commented
@akien-mga Sorry, pushed it into godotengine/godot-cpp instead of bastiaanolij/godot-cpp so the fix didn't show up:)

2021-11-10 07:53 UTC, akien-mga approved these changes

2021-11-10 07:53 UTC, merged

2021-11-10 07:53 UTC, akien-mga commented
Thanks!