Add Transform3D `translated_local`, `rotated_local`, `scaled_local`
godotengine/godot-cpp pull request #850
Opened 2022-09-18 21:36 UTC by Zylann

https://docs.godotengine.org/en/latest/classes/class_transform3d.html#class-transform3d-method-rotated-local
https://docs.godotengine.org/en/latest/classes/class_transform3d.html#class-transform3d-method-scaled-local
https://docs.godotengine.org/en/latest/classes/class_transform3d.html#class-transform3d-method-translated-local

2022-09-18 21:55 UTC, aaronfranke requested changes
See these Godot PRs: https://github.com/godotengine/godot/pull/57698 and https://github.com/godotengine/godot/pull/55923

I assume translated still has the hold behavior, so we'll need to update that one from core too.

2022-09-18 22:05 UTC, Zylann commented
Updated behavior of `translated`, `scaled` and `rotated`, which had old behavior.

2022-09-18 22:12 UTC, aaronfranke approved these changes

2022-09-19 07:31 UTC, merged

2022-09-19 07:32 UTC, akien-mga commented
Thanks!