Added support for typed ptr calls and added property info for ptr and ref
godotengine/godot-cpp pull request #950
Opened 2022-12-06 06:03 UTC by DmitriySalnikov

Supersedes #810
Rebased and fixed. Also added `PropertyInfo` for `Ref<T>`
#948 is required for a successful build

![image](https://user-images.githubusercontent.com/7782218/205829744-91985882-4068-473c-a8fe-65a7b5dbb7d0.png)

![Godot_v4 0-beta7_win64_7OvHJneZs2](https://user-images.githubusercontent.com/7782218/205828584-6c007ade-f541-4ca4-a181-fbc4f4a4f494.png)

2022-12-06 17:33 UTC, DmitriySalnikov commented
Rebased to master. Now it should build without problems.

2022-12-07 16:48 UTC, DmitriySalnikov commented
Do I need to do something else to continue the review?

2022-12-18 12:16 UTC, WildRackoon commented
This is spot on, but I am unsure how we can further reduce code duplication within some of those bindings files that are not generated.

2022-12-18 13:01 UTC, DmitriySalnikov commented
Macros can be used here. All 3 `VariantCaster`s can be replaced with such a macro:
```cpp
#define VARIANT_OBJECT_CAST(impl)                                      \
	template <class T>                                                 \
	struct VariantCaster impl {                                        \
		static _FORCE_INLINE_ T cast(const Variant &p_variant) {       \
			using TStripped = std::remove_pointer_t<T>;                \
			if constexpr (std::is_base_of<Object, TStripped>::value) { \
				return Object::cast_to<TStripped>(p_variant);          \
			} else {                                                   \
				return p_variant;                                      \
			}                                                          \
		}                                                              \
	}

// Will produce a warning. Error when building for Windows.
VARIANT_OBJECT_CAST();
VARIANT_OBJECT_CAST(<T &>);
VARIANT_OBJECT_CAST(<const T &>);
```

But there will still be a bunch of duplicated code nearby. I'll leave my changes here as is.
It may be worth creating a separate PR to remove all duplicates.

2023-01-11 11:58 UTC, akien-mga approved these changes

2023-01-11 13:09 UTC, DmitriySalnikov commented
After the rebase, I removed the examples here, but I think this is not a problem

2023-01-13 11:54 UTC, Faless requested changes
See the changes to use appropriate hint string (as in upstream godot).
The `class_name` is then copied automatically from the `hint_string` in `make_property_info`.

2023-01-13 11:54 UTC, Faless commented on include/godot_cpp/classes/ref.hpp
> +		return make_property_info(Variant::Type::OBJECT, "", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT, T::get_class_static());
```suggestion
		return make_property_info(Variant::Type::OBJECT, "", PROPERTY_HINT_RESOURCE_TYPE, T::get_class_static());
```

2023-01-13 11:54 UTC, Faless commented on include/godot_cpp/classes/ref.hpp
> +		return make_property_info(Variant::Type::OBJECT, "", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT, T::get_class_static());
```suggestion
		return make_property_info(Variant::Type::OBJECT, "", PROPERTY_HINT_RESOURCE_TYPE, T::get_class_static());
```

2023-01-13 13:53 UTC, DmitriySalnikov commented
Done.

2023-01-16 14:59 UTC, DmitriySalnikov commented
Do I need to do something else?

2023-01-17 10:31 UTC, akien-mga approved these changes

2023-01-17 10:31 UTC, merged